version: '3'

services:

  spring-boot-backend:
    container_name: spring-boot-backend
    build:
      context: backend/
      dockerfile: Dockerfile
    environment:
      SPRING_SERVER_PORT: 8080
    ports:
      - 8080:8080

  react-frontend:
    container_name: react-frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - spring-boot-backend
